build:
    environment:
        php:
            version: 7.1
checks:
    php:
        code_rating: true
        duplication: true
tools:
    external_code_coverage:
        timeout: 600
filter:
    paths: ["src/*"]
    excluded_paths:
        - "tests/"